/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package member_mangement_system_backend;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
